pipeline {
    agent any

    tools {
        maven 'maven'
    }

    stages {

        stage('Init') {
            steps {
                echo 'Welcome to the Binary Calculator Pipeline'
                sh 'pwd'
                sh 'ls -la'
            }
        }

        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }

        stage('Build') {
            steps {
                sh 'mvn package'
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploy stage (dummy stage)'
            }
        }
    }
}
