pipeline {
    agent any

    stages {

        stage('Init') {
            steps {
                echo 'Welcome to the Binary Calculator Pipeline'
                sh 'pwd'
                sh 'ls -la'
            }
        }

        stage('Test') {
            steps {
                dir('./BinaryCalculatorWebapp/') {
                    sh 'mvn test'
                }
            }
        }

        stage('Build') {
            steps {
                dir('./BinaryCalculatorWebapp/') {
                    sh 'mvn package'
                }
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploy stage (dummy stage)'
            }
        }
    }
}
